name: actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm i -g pnpm
    - run: pnpm install
    - run: pnpm bootstrap
    - run: pnpm test